### ISSUE TITLE
cant get update message in big gruops

### ISSUE THREAD

**Issue by sbh96** [rizaumami/tdcli.lua#14]
all things thats good ,but when i add account to group bigist then 10,000 but doesnt have any response for receive message from chat, but when i connect to my account with web or desktop platform apps and open directly which group dosnt get response  in my app , cli account  start to receive messages.
after some minutes stop working receive response  from that group .
i guess perhaps this is a bug .please solve this problem
note: i changed defulte value of
 ` tdcli_function ({ID="GetChats", offset_order_="9223372036854775807", offset_chat_id_=0, limit_=15000}, dl_cb, nil)`
but problem doesnt solved
please help me ,thankes

**Comment by sbh96** [comment]
hi again, i have problem in use if is user delete or kike from chat print this code value
where is problem?
`      if msg.content_.ID == "messageChatDeleteMember" then
        print("This is [ left ]")
        msg_type = 'MSG:Left'
      end`

**Comment by rizaumami** [comment]
Seems like your problems is `tdcli`'s bugs, not `tdcli.lua`.
Sorry, can't help you much as I don't have a group with more than 10k members, and `tdcli` development is kind of stopped/stalled.

**Comment by sbh96** [comment]
i solved this problem with openChat method thanks
