### ISSUE TITLE
tnx for script

### ISSUE THREAD

**Issue by mohamadkhoshnava** [rizaumami/tdcli.lua#3]
Hey 👋 

very very tnx for script lua
i use this in https://github.com/CRUELTM/cruel_bot

please see my source https://github.com/CRUELTM/cruel_bot 💓😝

سلام
خیلی خیلی تشکر میکنم از اسکریپت شما
من از این در سورس ربات خودم استفاده کردم

لطفا سورس من رو یک نگاه بندازید
https://github.com/CRUELTM/cruel_bot

تشکر

**Comment by rizaumami** [comment]
Thanx, glad if it helps.
IMHO, obsfucating your `bot.lua` is a useless effort, it's can be easily decompiled.
