### ISSUE TITLE
send Auth request

### ISSUE THREAD

**Issue by TeleCompiler** [rizaumami/tdcli.lua#7]
How can I send Auth Request?
I do not Know About auth in tdcli
how to get request code?

**Comment by rizaumami** [comment]
I don't know yet how to programatically Auth using `tdcli`.
But, you can just do authentication as usual by input your phone number and the received code.
Code will be sent to your currently active Telegram session.
Re-auth can be forced by deleting `.telegram-cli` configuration folder or `td.binlog` file
