### ISSUE TITLE
Run tdcli in windows 

### ISSUE THREAD

**Issue by TeleCompiler** [rizaumami/tdcli.lua#8]
I have windows server how can i use tdcli in windows ?
how can I run My codes in windows ? with which app ?

**Comment by rizaumami** [comment]
Sorry, can't help you with this as I don't have Windows server nor using Windows on my desktop.  
Perhaps these links can help you:

- http://www.lua.org/start.html
- https://github.com/LuaDist/Repository/wiki/LuaDist%3A-Installation

**Comment by rizaumami** [comment]
Closing this issue because of no further feedback.
If you still in need to run `tdcli` on Windows, perhaps [chocolatey](https://chocolatey.org/) will help.
