### ISSUE TITLE
Edit or delete new message

### ISSUE THREAD

**Issue by attarchi** [rizaumami/tdcli.lua#9]
hello
i can't edit or delete sent message, i think this because the sendMessage method return invalid message id.
sendMessage always return the 16 digits value.

**Comment by rizaumami** [comment]
This is `telegram-cli`s bug.
As you can see on [this page](https://valtman.name/telegram-cli), `telegram-cli` latest release was at December 2016. Seems it's been deprecated by eight months of Telegram updates.
